set(CMAKE_SYSTEM_NAME Windows)
set(CMAKE_SYSTEM_PROCESSOR AMD64)

if(DEFINED ENV{LLVM_MINGW_ROOT})
    set(LLVM_MINGW_ROOT "$ENV{LLVM_MINGW_ROOT}")
endif()

if(NOT CMAKE_C_COMPILER)
    set(CMAKE_C_COMPILER "${LLVM_MINGW_ROOT}/bin/clang.exe")
endif()
if(NOT CMAKE_CXX_COMPILER)
    set(CMAKE_CXX_COMPILER "${LLVM_MINGW_ROOT}/bin/clang++.exe")
endif()

set(CMAKE_C_COMPILER_TARGET x86_64-w64-windows-gnu CACHE STRING "" FORCE)
set(CMAKE_CXX_COMPILER_TARGET x86_64-w64-windows-gnu CACHE STRING "" FORCE)
set(CMAKE_TRY_COMPILE_TARGET_TYPE STATIC_LIBRARY)
